<?php echo $this->headScript()->appendFile($this->baseUrl() . '/js/item.js','text/javascript'); ?>

<h1>Editar item:</h1>

<a href='<?php echo $this->url ( array (
					'controller' => 'item',
					'action' => 'index' 
						), 'default', true )?>'>
						<img src="<?php echo $this->rootPath ?>images/back.png" title="VOLVER AL LISTADO" border="0"> Volver al listado</a>

<br/>

<div align="center">
	<?php echo $this->form; ?>
</div>

<div align="center">
	<?php echo $this->message; ?>
</div>

<div id="item_images" class="css-div-images">
	<?php
	$folder = $this->photosPath . $this->item->getPhotoDir() . '/';
	$filetype = '*.*';
	$files = glob($folder . $filetype);
	
	for ($i=0; $i<count($files); $i++) {
		echo "<img src='" . $this->rootPath . "/" . $files[$i] . "' />";
	}
	?>
</div>