<h1>Lista items:</h1>


<div align="right"><a
			href='<?php
			
echo $this->url ( array (
					'controller' => 'item',
					'action' => 'add' 
			), 'default', true )?>'>Agregar item</a>

			<br/>
			Total items registrados: <?php echo $this->totalItems;?>
			
</div>

<table border='0' align="center">
	<tr>
		<th>C&oacute;digo</th>
		<th>Nuevo c&oacute;digo</th>
		<th>Tipo</th>
		<th>Nombre</th>
		<th>Marca</th>
		<th>Procedencia</th>
		<th>Ubicaci&oacute;n</th>
		<th></th>
	</tr>

	<?php
	foreach ( $this->dataList as $item ) {
		?>
	<tr title="<?php echo $item->getComment(); ?>">
		<td><?php echo $item->getCode(); ?></td>
		<td><?php echo $item->getNewCode(); ?></td>
		<td><?php echo $item->getType()->getName(); ?></td>
		<td><?php echo $item->getName(); ?></td>
		<td><?php echo $item->getBrand()->getName(); ?></td>
		<td><?php echo $item->getOrigin()->getName(); ?></td>
		<td><?php echo $item->getLocation()->getName(); ?></td>
		<td align="center">
			<a
				href='<?php		
				echo $this->url ( array (
								'controller' => 'item',
								'action' => 'view',
								'id' => $item->getId () 
						), 'default', true )?>'>Ver
			</a>
			<br/>
			<a
				href='<?php		
				echo $this->url ( array (
								'controller' => 'item',
								'action' => 'edit',
								'id' => $item->getId () 
						), 'default', true )?>'>Modificar
			</a>
			<br/>
			<a
				href='<?php				
				echo $this->url ( array (
								'controller' => 'item',
								'action' => 'remove',
								'id' => $item->getId () 
						), 'default', true )?>'>Eliminar
			</a>
		</td>
	</tr>
	<?php
	}
	?>	
</table>

<div align="center" class="paginator_field">
			<?php echo $this->htmlPaginator; ?>
</div>

