<script>

$(document).ready(function () {

	$('#search').click(function(){
		alert('searching...');
	});	
});

</script>


<h1>Lista items:</h1>


<div align="right">
			<a
				href='<?php
				echo $this->url ( array (
						'controller' => 'item',
						'action' => 'add' 
				), 'default', true )?>'>
					<img src="<?php echo $this->rootPath ?>images/add.png" title="AGREGAR" border="0"> AGREGAR
			</a>

			<br/>
			<b>Total items registrados: <?php echo $this->totalItems;?> </b>
</div>

<div id='content_left'>
	<?php echo $this->searchPanel; ?>
</div>

<table border="0" align="center" class="css-table-index">
	<tr>
		<th>C&oacute;digo</th>
		<th>Nuevo c&oacute;digo</th>
		<th>Tipo</th>
		<th>Nombre</th>
		<th>Marca</th>
		<th>Procedencia</th>
		<th>Ubicaci&oacute;n</th>
		<th colspan="3"></th>
	</tr>

	<?php
	foreach ( $this->dataList as $item ) {
		?>
	<tr title="<?php echo $item->getComment(); ?>">
		<td><?php echo $item->getCode(); ?></td>
		<td><?php echo $item->getNewCode(); ?></td>
		<td><?php echo $item->getType()->getName(); ?></td>
		<td><?php echo $item->getName(); ?></td>
		<td><?php echo $item->getBrand()->getName(); ?></td>
		<td><?php echo $item->getOrigin()->getName(); ?></td>
		<td><?php echo $item->getLocation()->getName(); ?></td>
		<td>
			<a
				href='<?php		
				echo $this->url ( array (
								'controller' => 'item',
								'action' => 'view',
								'id' => $item->getId () 
						), 'default', true )?>'><img src="<?php echo $this->rootPath ?>images/view.png" title="VER">
			</a>
		</td>
		<td>
			<a
				href='<?php		
				echo $this->url ( array (
								'controller' => 'item',
								'action' => 'edit',
								'id' => $item->getId () 
						), 'default', true )?>'><img src="<?php echo $this->rootPath ?>images/edit.png" title="EDITAR">
			</a>
		</td>
		<td>
			<a
				href='<?php				
				echo $this->url ( array (
								'controller' => 'item',
								'action' => 'remove',
								'id' => $item->getId () 
						), 'default', true )?>'><img src="<?php echo $this->rootPath ?>images/remove.png" title="BORRAR">
			</a>
		</td>
	</tr>
	<?php
	}
	?>	
</table>

<div align="center" class="paginator_field">
			<?php echo $this->htmlPaginator; ?>
</div>

