<h1>Lista tipos:</h1>


<div align="right">
			<a
				href='<?php
				echo $this->url ( array (
						'controller' => 'itemtype',
						'action' => 'add' 
				), 'default', true )?>'>
					<img src="<?php echo $this->rootPath ?>images/add.png" title="AGREGAR" border="0"> AGREGAR
			</a>
</div>

<table border="0" align="center" class="css-table-index">
	<tr>
		<th>Nombre</th>
		<th>Descripci&oacute;n</th>
		<th colspan="3"></th>
	</tr>

	<?php
	foreach ( $this->dataList as $itemType ) {
		?>
	<tr>
		<td><?php echo $itemType->getName(); ?></td>
		<td><?php echo $itemType->getDescription(); ?></td>
		<td>
			<?php if($itemType->getName() != "- Seleccionar -"){ ?>
			<a
				href='<?php		
				echo $this->url ( array (
								'controller' => 'itemtype',
								'action' => 'view',
								'id' => $itemType->getId () 
						), 'default', true )?>'><img src="<?php echo $this->rootPath ?>images/view.png" title="VER">
			</a>
			<?php } ?>
		</td>
		<td>
			<?php if($itemType->getName() != "- Seleccionar -"){ ?>
			<a
				href='<?php		
				echo $this->url ( array (
								'controller' => 'itemtype',
								'action' => 'edit',
								'id' => $itemType->getId () 
						), 'default', true )?>'><img src="<?php echo $this->rootPath ?>images/edit.png" title="EDITAR">
			</a>
			<?php } ?>
		</td>
		<td>
			<?php if($itemType->getName() != "- Seleccionar -"){ ?>
			<a
				href='<?php				
				echo $this->url ( array (
								'controller' => 'itemtype',
								'action' => 'remove',
								'id' => $itemType->getId () 
						), 'default', true )?>'><img src="<?php echo $this->rootPath ?>images/remove.png" title="BORRAR">
			</a>
			<?php } ?>
		</td>
	</tr>
	<?php
	}
	?>	
</table>